#
# Atlas Base Dockerfile
#
# https://git.soma.salesforce.com/atlas/docker-image-base/new/master
#

# Pull base image.
FROM centos

# Create common directories
RUN mkdir /app
RUN mkdir /data
RUN mkdir /config

# Install RPM Packages
RUN yum install -y git
RUN yum install -y augeas
RUN yum install -y ruby

# Install Gem Packages
RUN gem install --config-file=/root/.gemrc rack -v 1.4.5
