#
# Atlas Base Dockerfile
#
# https://git.soma.salesforce.com/atlas/docker-image-base/new/master
#

# Pull base image.
FROM centos

# Create common directories
RUN mkdir /app
RUN mkdir /data
RUN mkdir /config

# Add yum repositories
ADD rypple-centos6-epel.repo /etc/yum.repos.d/rypple-centos6-epel.repo

# Install Packages
RUN yum install -y git
